norm_wave:
  sample_rate   : 24000
  norm_db       : -3.0
  sil_threshold : 1.0
  sil_duration  : 0.1
  preemph       : 0.97

mel_spec:
  sample_rate   : 24000
  fft_window_ms : 50.0
  fft_hop_ms    : 12.5
  n_fft         : 2048
  f_min         : 50.0
  n_mels        : 80
  ref_db        : 20.0
  dc_db         : 100.0

mel2embed:
  seg_len : 128

wav_dir : './dataset/jvs/wav'
mel_dir : './dataset/jvs/mel'
agl_dir : './dataset/jvs/agl'
emb_dir : './dataset/jvs/emb'

highpass_cutoff : 70.0

sample_rate : 22050
fft_size    : 1024
num_mels    : 80
fmin        : 0  # Set this to 55 if your speaker is male! if female, 95 should help taking off noise.
fmax        : 8000  # To be increased/reduced depending on data.
hop_size    : 256
win_length  : 1024
window      : 'hann'
