norm_wave:
  sample_rate   : 24000
  norm_db       : -3.0
  sil_threshold : 1.0
  sil_duration  : 0.1
  preemph       : 0.97

mel_spec:
  sample_rate   : 24000
  fft_window_ms : 50.0
  fft_hop_ms    : 12.5
  n_fft         : 2048
  f_min         : 50.0
  n_mels        : 80
  ref_db        : 20.0
  dc_db         : 100.0

mel2embed:
  seg_len : 128

wav_dir : './dataset/jvs/wav'
mel_dir : './dataset/jvs/mel'
agl_dir : './dataset/jvs/agl'
emb_dir : './dataset/jvs/emb'

# Wavenet
sample_rate     : 22050
highpass_cutoff : 70.0
fft_size        : 1024
hop_size        : 256
win_length      : 1024
window          : 'hann'
num_mels        : 80
fmin            : 125
fmax            : 7600

log_scale_min : -16.0

# Wavenet model
wavenet_model:
  out_channels : 30  # num_mixture * 3 (pi, mean, log_scale)
  layers       : 24
  stacks       : 4
  residual_channels : 128
  gate_channels : 256
  skip_out_channels : 128
  kernel_size : 3
  dropout : 0.0

  cin_channels : 80
  gin_channels : -1
  n_speakers : -1  # 7 for CMU ARCTIC
  weight_normalization : true
  upsample_conditional_features : true
  upsample_scales : [4, 4, 4, 4]
  freq_axis_kernel_size : 3
