use_same_speaker : true
no_train         : false
model_load_path  : null
gen_spec_fig     : true
gen_mel_wave     : true

seg_len     : 128
nmels       : 80
style_dim   : 256
dim_neck    : 32
lstm_stride : 8

log_interval   : 100
batch_size     : 8

stages:
  -
    optimizer  : 'adam'
    lr         : 1.e-3
    num_epochs : 100
    patience   : 10
  -
    optimizer  : 'sgd'
    lr         : 1.e-1
    momentum   : 0.9
    num_epochs : 200
    patience   : 20

vgg_weight  : 0.01
ssim_weight : 0.1

train_dataset:
  num_repeats   : 100
  speaker_start : 0
  speaker_end   : 80
  speech_start  : 0
  speech_end    : 80

valdt_dataset:
  num_repeats   : 20
  speaker_start : 80
  speaker_end   : 90
  speech_start  : 80
  speech_end    : 90

tests_dataset:
  num_repeats   : 1
  speaker_start : 90
  speaker_end   : 100
  speech_start  : 90
  speech_end    : 100

mel_dir : './dataset/jvs/mel'
agl_dir : './dataset/jvs/agl'
emb_dir : './dataset/jvs/emb'

predict:
  source_speaker : 'jvs091'
  target_speaker : 'jvs092'
  speech         : 'VOICEACTRESS100_091'

mel_spec:
  sample_rate   : 24000
  fft_window_ms : 50.0
  fft_hop_ms    : 12.5
  n_fft         : 2048
  f_min         : 50.0
  n_mels        : 80
  ref_db        : 20.0
  dc_db         : 100.0

spec_fig:
  min_db : -1.75
  max_db : 0.75
