seg_len     : 128
nmels       : 80
style_dim   : 256
dim_neck    : 32
lstm_stride : 8

num_epochs       : 100
log_interval     : 100
lr               : 1.e-03
clip_grad_norm   : 1
batch_size       : 8

train_dataset:
  num_repeats   : 100
  speaker_start : 0
  speaker_end   : 80
  speech_start  : 0
  speech_end    : 80

valdt_dataset:
  num_repeats   : 20
  speaker_start : 80
  speaker_end   : 100
  speech_start  : 80
  speech_end    : 100

tests_dataset:
  speaker_start : 90
  speaker_end   : 100
  speech_start  : 90
  speech_end    : 100

use_same_speaker : false

mel_path : '/home/g2181479/vc-beta/vc3/mel-jvs'