use_same_speaker : true
no_train         : false
model_load_path  : null
gen_spec_fig     : true
gen_mel_wave     : true

log_interval : 100
batch_size   : 8

stages:
  -
    optimizer  : 'adam'
    lr         : 1.e-3
    num_epochs : 100
    patience   : 10
  -
    optimizer  : 'sgd'
    lr         : 1.e-1
    momentum   : 0.9
    num_epochs : 200
    patience   : 20

vgg_weight  : 0.01
ssim_weight : 0.1

train_dataset:
  num_repeats   : 100
  speaker_start : 0
  speaker_end   : 80
  speech_start  : 0
  speech_end    : 80

valdt_dataset:
  num_repeats   : 20
  speaker_start : 80
  speaker_end   : 90
  speech_start  : 80
  speech_end    : 90

tests_dataset:
  num_repeats   : 1
  speaker_start : 90
  speaker_end   : 100
  speech_start  : 90
  speech_end    : 100

wav_dir : './dataset/jvs/wav'
mel_dir : './dataset/jvs/mel'
emb_dir : './dataset/jvs/emb'

predict:
  source_speaker : 'jvs091'
  target_speaker : 'jvs092'
  speech         : 'VOICEACTRESS100_091'

highpass_cutoff : 70.0

# mel settings
sample_rate : 22050
fft_size    : 1024
num_mels    : 80
fmin        : 0     # Set this to 55 if your speaker is male! if female, 95 should help taking off noise.
fmax        : 8000  # To be increased/reduced depending on data.
hop_size    : 256
win_length  : 1024
window      : 'hann'

# sample_rate : 24000
# fft_size    : 2048
# num_mels    : 80
# fmin        : 80     # Set this to 55 if your speaker is male! if female, 95 should help taking off noise.
# fmax        : 7600  # To be increased/reduced depending on data.
# hop_size    : 300
# win_length  : 1200
# window      : 'hann'

mel2embed:
  seg_len : 128

# model setting
seg_len     : 128
style_dim   : 256
dim_neck    : 32
lstm_stride : 8