seg_len    : 128
nmels      : 80
style_dim  : 256
dim_neck   : 32
lstm_stride: 32

epochs        : 300
num_repeats   : 100
num_test_repeats: 20
log_interval  : 100
lr            : 0.001
clip_grad_norm: 1
batch_size    : 8

num_speakers: 80
num_speeches: 80