use_same_speaker : true
no_train         : true
model_load_path  : 'wd/apple/202206/05/101857/cp/best_train.pth'
gen_spec_fig     : true
gen_mel_wave     : true

n_mels      : 80
seg_len     : 128
style_dim   : 256
dim_neck    : 32
lstm_stride : 8

log_interval   : 100
batch_size     : 8

stages:
  -
    optimizer  : 'adam'
    lr         : 1.e-3
    num_epochs : 100
    patience   : 10
  -
    optimizer  : 'sgd'
    lr         : 1.e-1
    momentum   : 0.9
    num_epochs : 200
    patience   : 20

vgg_weight  : 0.01
ssim_weight : 0.1

train_dataset:
  num_repeats   : 100
  speaker_start : 0
  speaker_end   : 80
  speech_start  : 0
  speech_end    : 80

valdt_dataset:
  num_repeats   : 20
  speaker_start : 80
  speaker_end   : 90
  speech_start  : 80
  speech_end    : 90

tests_dataset:
  num_repeats   : 1
  speaker_start : 90
  speaker_end   : 100
  speech_start  : 90
  speech_end    : 100

wav_dir : './dataset/jvs/wav'
mel_dir : './dataset/jvs/mel'
agl_dir : './dataset/jvs/agl'
emb_dir : './dataset/jvs/emb'

predict:
  source_speaker : 'jvs091'
  target_speaker : 'jvs092'
  speech         : 'VOICEACTRESS100_091'

mel_spec:
  sample_rate   : 24000
  fft_window_ms : 50.0
  fft_hop_ms    : 12.5
  n_fft         : 2048
  f_min         : 50.0
  n_mels        : 80
  ref_db        : 20.0
  dc_db         : 100.0

spec_fig:
  min_db : -1.75
  max_db : 0.75


# Wavenet
sample_rate     : 22050
highpass_cutoff : 70.0
fft_size        : 1024
hop_size        : 256
win_length      : 1024
window          : 'hann'
num_mels        : 80
fmin            : 125
fmax            : 7600

log_scale_min : -16.0

# Wavenet model
wavenet_model:
  out_channels : 30  # num_mixture * 3 (pi, mean, log_scale)
  layers       : 24
  stacks       : 4
  residual_channels : 128
  gate_channels : 256
  skip_out_channels : 128
  kernel_size : 3
  dropout : 0.0

  cin_channels : 80
  gin_channels : -1
  n_speakers : -1  # 7 for CMU ARCTIC
  weight_normalization : true
  upsample_conditional_features : true
  upsample_scales : [4, 4, 4, 4]
  freq_axis_kernel_size : 3
