# Root
use_same_speaker : true
model_load_path  : null
xvec_model_path  : 'dest/2_train_xvector/20220621/220352/cp/0_best_valdt.pth'  # 32x128
# xvec_model_path  : 'dest/2_train_xvector/20220622/142211/cp/0_best_valdt.pth'  # 32x256
need_predict     : true

# ML
log_interval : 100
batch_size   : 8
speaker_size : 32

stages:
  -
    optimizer  : 'adam'
    lr         : 1.e-3
    num_epochs : 200
    patience   : 20
  -
    optimizer  : 'sgd'
    lr         : 1.e-2
    momentum   : 0.9
    num_epochs : 400
    patience   : 40

vgg_weight  : 0.01
sim_weight : 0.1

train_dataset:
  num_repeats   : 100
  speaker_start : 0
  speaker_end   : 80
  speech_start  : 0
  speech_end    : 80

valdt_dataset:
  num_repeats   : 20
  speaker_start : 80
  speaker_end   : 90
  speech_start  : 80
  speech_end    : 90

tests_dataset:
  num_repeats   : 1
  speaker_start : 90
  speaker_end   : 100
  speech_start  : 90
  speech_end    : 100

# Dataset
wav_dir : './dataset/seiren_jvs011/wav'
mel_dir : './dataset/seiren_jvs011/mel'
emb_dir : './dataset/jvs_ver1/emb_spk32_dim128'

predict:
  source_speaker : 'jvs091'
  target_speaker : 'jvs092'
  speech         : 'VOICEACTRESS100_091'

# Audio
highpass_cutoff : 70.0

vocoder : 'melgan'

melgan:
  sample_rate : 24000
  fft_size    : 1024
  num_mels    : 80
  fmin        : 80    # Set this to 55 if your speaker is male! if female, 95 should help taking off noise.
  fmax        : 7600  # To be increased/reduced depending on data.
  hop_size    : 300
  win_length  : 1024
  window      : 'hann'

  wavegan_model_path : './model/train_nodev_jsut_multi_band_melgan.v2/checkpoint-1000000steps.pkl'
  wavegan_stats_path : './model/train_nodev_jsut_multi_band_melgan.v2/stats.h5'
  # wavegan_model_path : './model/TSUKUYOMICHAN_MODEL_v.1.2.0/VOCODER/checkpoint-300000steps.pkl'
  # wavegan_stats_path : './model/TSUKUYOMICHAN_MODEL_v.1.2.0/VOCODER/stats.h5'

waveglow:
  sample_rate : 22050
  fft_size    : 1024
  num_mels    : 80
  fmin        : 0     # Set this to 55 if your speaker is male! if female, 95 should help taking off noise.
  fmax        : 8000  # To be increased/reduced depending on data.
  hop_size    : 256
  win_length  : 1024
  window      : 'hann'

# Model (xvector)
seg_len     : 128
style_dim   : 128

# Model (vc)
dim_neck    : 32
lstm_stride : 8
