# Root
use_same_speaker : true
model_load_path  : 'wd/train_xvector/20220618/033433/cp/0_best_train.pth'

# ML
log_interval : 100
batch_size   : 8

stages:
  -
    mode       : 'large'
    optimizer  : 'adam'
    lr         : 1.e-3
    num_epochs : 400
    patience   : 20
  # -
  #   mode       : 'large'
  #   optimizer  : 'sgd'
  #   lr         : 1.e-2
  #   momentum   : 0.9
  #   num_epochs : 400
  #   patience   : 20

vgg_weight  : 0.01
ssim_weight : 0.1

small_dataset:
  num_repeats   : 100
  speaker_start : 0
  speaker_end   : 20
  speech_start  : 0
  speech_end    : 80
medium_dataset:
  num_repeats   : 100
  speaker_start : 0
  speaker_end   : 40
  speech_start  : 0
  speech_end    : 80
large_dataset:
  num_repeats   : 100
  speaker_start : 0
  speaker_end   : 80
  speech_start  : 0
  speech_end    : 80

# Dataset
wav_dir : './dataset/seiren_jvs011/wav'
lab_dir : './dataset/seiren_jvs011/lab'
mel_dir : './dataset/seiren_jvs011/mel'
emb_dir : './dataset/seiren_jvs011/emb'

kana_path : './dataset/jvs_hiho/voiceactoress100_spaced_julius.txt'
hmm_path  : './dataset/dictation-kit-4.5/model/phone_m/jnas-mono-16mix-gid.binhmm'

# Audio
highpass_cutoff : 70.0

vocoder : 'melgan'

melgan:
  sample_rate : 24000
  fft_size    : 1024
  num_mels    : 80
  fmin        : 80    # Set this to 55 if your speaker is male! if female, 95 should help taking off noise.
  fmax        : 7600  # To be increased/reduced depending on data.
  hop_size    : 300
  win_length  : 1024
  window      : 'hann'

  wavegan_model_path : './model/train_nodev_jsut_multi_band_melgan.v2/checkpoint-1000000steps.pkl'
  wavegan_stats_path : './model/train_nodev_jsut_multi_band_melgan.v2/stats.h5'
  # wavegan_model_path : './model/TSUKUYOMICHAN_MODEL_v.1.2.0/VOCODER/checkpoint-300000steps.pkl'
  # wavegan_stats_path : './model/TSUKUYOMICHAN_MODEL_v.1.2.0/VOCODER/stats.h5'

waveglow:
  sample_rate : 22050
  fft_size    : 1024
  num_mels    : 80
  fmin        : 0     # Set this to 55 if your speaker is male! if female, 95 should help taking off noise.
  fmax        : 8000  # To be increased/reduced depending on data.
  hop_size    : 256
  win_length  : 1024
  window      : 'hann'

# Model (xvector)
seg_len     : 128
style_dim   : 128
