# Root
extract_envelope : false
model_load_path  : 'wd/3_train_xvector/20220619/192126/cp/1_best_valdt.pth'

# ML
num_workers   : 32
log_interval  : 100
batch_size    : 80

stages:
  -
    optimizer  : 'adam'
    lr         : 1.e-3
    num_epochs : 2000
    patience   : 20
  -
    optimizer  : 'sgd'
    lr         : 1.e-2
    momentum   : 0.9
    num_epochs : 2000
    patience   : 20

train_dataset:
  num_repeats   : 100
  speaker_start : 0
  speaker_end   : 80
  phoneme_start : 0
  phoneme_end   : 3600

valdt_dataset:
  num_repeats   : 40
  speaker_start : 0
  speaker_end   : 80
  phoneme_start : 3600
  phoneme_end   : 4000

tests_dataset:
  num_repeats   : 40
  speaker_start : 0
  speaker_end   : 80
  phoneme_start : 4000
  phoneme_end   : 4400

# Dataset
wav_dir : './dataset/seiren_jvs011/wav'
lab_dir : './dataset/seiren_jvs011/lab'
emb_dir : './dataset/seiren_jvs011/emb'
mel_dir : './dataset/seiren_jvs011/mel'

kana_path : './dataset/jvs_hiho/voiceactoress100_spaced_julius.txt'
hmm_path  : './dataset/dictation-kit-4.5/model/phone_m/jnas-mono-16mix-gid.binhmm'

# Audio
highpass_cutoff : 70.0

vocoder : 'melgan'

sample_rate : 24000
fft_size    : 1024
num_mels    : 80
fmin        : 80    # Set this to 55 if your speaker is male! if female, 95 should help taking off noise.
fmax        : 7600  # To be increased/reduced depending on data.
hop_size    : 120
win_length  : 1024
window      : 'hann'

# Model (xvector)
seg_len     : 128
style_dim   : 128

pnm_len : 32