# Root
extract_envelope : false
model_load_path  : null
dataset_dynamic  : true

# ML
log_interval : 100
batch_size   : 80

stages:
  -
    optimizer  : 'adam'
    lr         : 1.e-3
    num_epochs : 2000
    patience   : 20
  -
    optimizer  : 'sgd'
    lr         : 1.e-1
    momentum   : 0.9
    num_epochs : 2000
    patience   : 20

train_dataset:
  num_repeats   : 100
  speaker_start : 0
  speaker_end   : 80
  phoneme_start : 0
  phoneme_end   : 5120

valdt_dataset:
  num_repeats   : 40
  speaker_start : 0
  speaker_end   : 80
  phoneme_start : 5120
  phoneme_end   : 5760

tests_dataset:
  num_repeats   : 40
  speaker_start : 0
  speaker_end   : 80
  phoneme_start : 5760
  phoneme_end   : 6400

# Dataset
wav_dir : './dataset/seiren_jvs011/wav'
lab_dir : './dataset/seiren_jvs011/lab'
pnm_mel_dir : './dataset/seiren_jvs011/pnm_mel_all'  # Save directory for mel-spectrogram
pnm_spc_dir : './dataset/seiren_jvs011/pnm_spc_all'  # Save directory for spectrogram
pnm_dir : './dataset/seiren_jvs011/pnm_mel_all'      # Load target directory
emb_dir : './dataset/seiren_jvs011/emb_mel_all'
mel_dir : './dataset/seiren_jvs011/mel'

kana_path : './dataset/jvs_hiho/voiceactoress100_spaced_julius.txt'
hmm_path  : './dataset/dictation-kit-4.5/model/phone_m/jnas-mono-16mix-gid.binhmm'

# Audio
highpass_cutoff : 70.0

vocoder : 'melgan'

sample_rate : 24000
fft_size    : 1024
num_mels    : 80
fmin        : 80    # Set this to 55 if your speaker is male! if female, 95 should help taking off noise.
fmax        : 7600  # To be increased/reduced depending on data.
hop_size    : 120   # WORLD
win_length  : 1024
window      : 'hann'

# Model (xvector)
seg_len     : 128
style_dim   : 128

pnm_len : 32