# Root
extract_envelope : false
model_load_path  : null

# ML
log_interval  : 100
batch_size    : 32
speaker_size  : 8

stages:
  -
    optimizer  : 'adam'
    lr: 1.e-3
    num_epochs : 5000
    patience   : 100

train_dataset:
  num_repeats   : 100
  phoneme_start : 0
  phoneme_end   : 480

valdt_dataset:
  num_repeats   : 40
  phoneme_start : 480
  phoneme_end   : 500

tests_dataset:
  num_repeats   : 40
  phoneme_start : 500
  phoneme_end   : 520 # max: 539

# Dataset
wav_dir : './dataset/jvs_ver1/wav'
bak_dir : './dataset/jvs_ver1/wav_bak'
lab_dir : './dataset/jvs_ver1/lab'
emb_dir : './dataset/jvs_ver1/emb_spk8_dim32'

kana_path : './dataset/jvs_hiho/voiceactoress100_spaced_julius.txt'
hmm_path  : './dataset/dictation-kit-4.5/model/phone_m/jnas-mono-16mix-gid.binhmm'

# Audio
highpass_cutoff : 70.0

vocoder : 'melgan'

sample_rate : 24000
fft_size    : 1024
num_mels    : 80
fmin        : 80    # Set this to 55 if your speaker is male! if female, 95 should help taking off noise.
fmax        : 7600  # To be increased/reduced depending on data.
hop_size    : 120
win_length  : 1024
window      : 'hann'

# Model (xvector)
seg_len     : 128
style_dim   : 32

pnm_len : 32