from typing import OrderedDict
import torch

model_dict ={
    'encoder.convolutions.0.0.conv.weight': 'content_enc.conv1.layer.weight',
    'encoder.convolutions.0.0.conv.bias': 'content_enc.conv1.layer.bias',
    'encoder.convolutions.0.1.weight': 'content_enc.conv1.bn.weight',
    'encoder.convolutions.0.1.bias': 'content_enc.conv1.bn.bias',
    'encoder.convolutions.0.1.running_mean': 'content_enc.conv1.bn.running_mean',
    'encoder.convolutions.0.1.running_var': 'content_enc.conv1.bn.running_var',
    'encoder.convolutions.0.1.num_batches_tracked': 'content_enc.conv1.bn.num_batches_tracked',
    'encoder.convolutions.1.0.conv.weight': 'content_enc.conv2.layer.weight',
    'encoder.convolutions.1.0.conv.bias': 'content_enc.conv2.layer.bias',
    'encoder.convolutions.1.1.weight': 'content_enc.conv2.bn.weight',
    'encoder.convolutions.1.1.bias': 'content_enc.conv2.bn.bias',
    'encoder.convolutions.1.1.running_mean': 'content_enc.conv2.bn.running_mean',
    'encoder.convolutions.1.1.running_var': 'content_enc.conv2.bn.running_var',
    'encoder.convolutions.1.1.num_batches_tracked': 'content_enc.conv2.bn.num_batches_tracked',
    'encoder.convolutions.2.0.conv.weight': 'content_enc.conv3.layer.weight',
    'encoder.convolutions.2.0.conv.bias': 'content_enc.conv3.layer.bias',
    'encoder.convolutions.2.1.weight': 'content_enc.conv3.bn.weight',
    'encoder.convolutions.2.1.bias': 'content_enc.conv3.bn.bias',
    'encoder.convolutions.2.1.running_mean': 'content_enc.conv3.bn.running_mean',
    'encoder.convolutions.2.1.running_var': 'content_enc.conv3.bn.running_var',
    'encoder.convolutions.2.1.num_batches_tracked': 'content_enc.conv3.bn.num_batches_tracked',
    'encoder.lstm.weight_ih_l0': 'content_enc.lstm.weight_ih_l0',
    'encoder.lstm.weight_hh_l0': 'content_enc.lstm.weight_hh_l0',
    'encoder.lstm.bias_ih_l0': 'content_enc.lstm.bias_ih_l0',
    'encoder.lstm.bias_hh_l0': 'content_enc.lstm.bias_hh_l0',
    'encoder.lstm.weight_ih_l0_reverse': 'content_enc.lstm.weight_ih_l0_reverse',
    'encoder.lstm.weight_hh_l0_reverse': 'content_enc.lstm.weight_hh_l0_reverse',
    'encoder.lstm.bias_ih_l0_reverse': 'content_enc.lstm.bias_ih_l0_reverse',
    'encoder.lstm.bias_hh_l0_reverse': 'content_enc.lstm.bias_hh_l0_reverse',
    'encoder.lstm.weight_ih_l1': 'content_enc.lstm.weight_ih_l1',
    'encoder.lstm.weight_hh_l1': 'content_enc.lstm.weight_hh_l1',
    'encoder.lstm.bias_ih_l1': 'content_enc.lstm.bias_ih_l1',
    'encoder.lstm.bias_hh_l1': 'content_enc.lstm.bias_hh_l1',
    'encoder.lstm.weight_ih_l1_reverse': 'content_enc.lstm.weight_ih_l1_reverse',
    'encoder.lstm.weight_hh_l1_reverse': 'content_enc.lstm.weight_hh_l1_reverse',
    'encoder.lstm.bias_ih_l1_reverse': 'content_enc.lstm.bias_ih_l1_reverse',
    'encoder.lstm.bias_hh_l1_reverse': 'content_enc.lstm.bias_hh_l1_reverse',
    'decoder.lstm1.weight_ih_l0': 'decoder.lstm1.weight_ih_l0',
    'decoder.lstm1.weight_hh_l0': 'decoder.lstm1.weight_hh_l0',
    'decoder.lstm1.bias_ih_l0': 'decoder.lstm1.bias_ih_l0',
    'decoder.lstm1.bias_hh_l0': 'decoder.lstm1.bias_hh_l0',
    'decoder.convolutions.0.0.conv.weight': 'decoder.conv1.layer.weight',
    'decoder.convolutions.0.0.conv.bias': 'decoder.conv1.layer.bias',
    'decoder.convolutions.0.1.weight': 'decoder.conv1.bn.weight',
    'decoder.convolutions.0.1.bias': 'decoder.conv1.bn.bias',
    'decoder.convolutions.0.1.running_mean': 'decoder.conv1.bn.running_mean',
    'decoder.convolutions.0.1.running_var': 'decoder.conv1.bn.running_var',
    'decoder.convolutions.0.1.num_batches_tracked': 'decoder.conv1.bn.num_batches_tracked',
    'decoder.convolutions.1.0.conv.weight': 'decoder.conv2.layer.weight',
    'decoder.convolutions.1.0.conv.bias': 'decoder.conv2.layer.bias',
    'decoder.convolutions.1.1.weight': 'decoder.conv2.bn.weight',
    'decoder.convolutions.1.1.bias': 'decoder.conv2.bn.bias',
    'decoder.convolutions.1.1.running_mean': 'decoder.conv2.bn.running_mean',
    'decoder.convolutions.1.1.running_var': 'decoder.conv2.bn.running_var',
    'decoder.convolutions.1.1.num_batches_tracked': 'decoder.conv2.bn.num_batches_tracked',
    'decoder.convolutions.2.0.conv.weight': 'decoder.conv3.layer.weight',
    'decoder.convolutions.2.0.conv.bias': 'decoder.conv3.layer.bias',
    'decoder.convolutions.2.1.weight': 'decoder.conv3.bn.weight',
    'decoder.convolutions.2.1.bias': 'decoder.conv3.bn.bias',
    'decoder.convolutions.2.1.running_mean': 'decoder.conv3.bn.running_mean',
    'decoder.convolutions.2.1.running_var': 'decoder.conv3.bn.running_var',
    'decoder.convolutions.2.1.num_batches_tracked': 'decoder.conv3.bn.num_batches_tracked',
    'decoder.lstm2.weight_ih_l0': 'decoder.lstm2.weight_ih_l0',
    'decoder.lstm2.weight_hh_l0': 'decoder.lstm2.weight_hh_l0',
    'decoder.lstm2.bias_ih_l0': 'decoder.lstm2.bias_ih_l0',
    'decoder.lstm2.bias_hh_l0': 'decoder.lstm2.bias_hh_l0',
    'decoder.lstm2.weight_ih_l1': 'decoder.lstm2.weight_ih_l1',
    'decoder.lstm2.weight_hh_l1': 'decoder.lstm2.weight_hh_l1',
    'decoder.lstm2.bias_ih_l1': 'decoder.lstm2.bias_ih_l1',
    'decoder.lstm2.bias_hh_l1': 'decoder.lstm2.bias_hh_l1',
    'decoder.linear_projection.linear_layer.weight': 'decoder.line.layer.weight',
    'decoder.linear_projection.linear_layer.bias': 'decoder.line.layer.bias',
    'postnet.convolutions.0.0.conv.weight': 'postnet.conv1.layer.weight',
    'postnet.convolutions.0.0.conv.bias': 'postnet.conv1.layer.bias',
    'postnet.convolutions.0.1.weight': 'postnet.conv1.bn.weight',
    'postnet.convolutions.0.1.bias': 'postnet.conv1.bn.bias',
    'postnet.convolutions.0.1.running_mean': 'postnet.conv1.bn.running_mean',
    'postnet.convolutions.0.1.running_var': 'postnet.conv1.bn.running_var',
    'postnet.convolutions.0.1.num_batches_tracked': 'postnet.conv1.bn.num_batches_tracked',
    'postnet.convolutions.1.0.conv.weight': 'postnet.conv2.layer.weight',
    'postnet.convolutions.1.0.conv.bias': 'postnet.conv2.layer.bias',
    'postnet.convolutions.1.1.weight': 'postnet.conv2.bn.weight',
    'postnet.convolutions.1.1.bias': 'postnet.conv2.bn.bias',
    'postnet.convolutions.1.1.running_mean': 'postnet.conv2.bn.running_mean',
    'postnet.convolutions.1.1.running_var': 'postnet.conv2.bn.running_var',
    'postnet.convolutions.1.1.num_batches_tracked': 'postnet.conv2.bn.num_batches_tracked',
    'postnet.convolutions.2.0.conv.weight': 'postnet.conv3.layer.weight',
    'postnet.convolutions.2.0.conv.bias': 'postnet.conv3.layer.bias',
    'postnet.convolutions.2.1.weight': 'postnet.conv3.bn.weight',
    'postnet.convolutions.2.1.bias': 'postnet.conv3.bn.bias',
    'postnet.convolutions.2.1.running_mean': 'postnet.conv3.bn.running_mean',
    'postnet.convolutions.2.1.running_var': 'postnet.conv3.bn.running_var',
    'postnet.convolutions.2.1.num_batches_tracked': 'postnet.conv3.bn.num_batches_tracked',
    'postnet.convolutions.3.0.conv.weight': 'postnet.conv4.layer.weight',
    'postnet.convolutions.3.0.conv.bias': 'postnet.conv4.layer.bias',
    'postnet.convolutions.3.1.weight': 'postnet.conv4.bn.weight',
    'postnet.convolutions.3.1.bias': 'postnet.conv4.bn.bias',
    'postnet.convolutions.3.1.running_mean': 'postnet.conv4.bn.running_mean',
    'postnet.convolutions.3.1.running_var': 'postnet.conv4.bn.running_var',
    'postnet.convolutions.3.1.num_batches_tracked': 'postnet.conv4.bn.num_batches_tracked',
    'postnet.convolutions.4.0.conv.weight': 'postnet.conv5.layer.weight',
    'postnet.convolutions.4.0.conv.bias': 'postnet.conv5.layer.bias',
    'postnet.convolutions.4.1.weight': 'postnet.conv5.bn.weight',
    'postnet.convolutions.4.1.bias': 'postnet.conv5.bn.bias',
    'postnet.convolutions.4.1.running_mean': 'postnet.conv5.bn.running_mean',
    'postnet.convolutions.4.1.running_var': 'postnet.conv5.bn.running_var',
    'postnet.convolutions.4.1.num_batches_tracked': 'postnet.conv5.bn.num_batches_tracked',
}

style_dict = {
    'module.lstm.weight_ih_l0': 'style_enc.lstm.weight_ih_l0',
    'module.lstm.weight_hh_l0': 'style_enc.lstm.weight_hh_l0',
    'module.lstm.bias_ih_l0': 'style_enc.lstm.bias_ih_l0',
    'module.lstm.bias_hh_l0': 'style_enc.lstm.bias_hh_l0',
    'module.lstm.weight_ih_l1': 'style_enc.lstm.weight_ih_l1',
    'module.lstm.weight_hh_l1': 'style_enc.lstm.weight_hh_l1',
    'module.lstm.bias_ih_l1': 'style_enc.lstm.bias_ih_l1',
    'module.lstm.bias_hh_l1': 'style_enc.lstm.bias_hh_l1',
    'module.lstm.weight_ih_l2': 'style_enc.lstm.weight_ih_l2',
    'module.lstm.weight_hh_l2': 'style_enc.lstm.weight_hh_l2',
    'module.lstm.bias_ih_l2': 'style_enc.lstm.bias_ih_l2',
    'module.lstm.bias_hh_l2': 'style_enc.lstm.bias_hh_l2',
    'module.embedding.weight': 'style_enc.line.layer.weight',
    'module.embedding.bias': 'style_enc.line.layer.bias',
}

model = torch.load('model/autovc.ckpt')['model']
style = torch.load('model/3000000-BL.ckpt')['model_b']

model = [(model_dict[k], v) for k, v in model.items()]
style = [(style_dict[k], v) for k, v in style.items()]

pos = 37
for i in range(len(style)):
    model.insert(i + 37, style[i])

model = OrderedDict(model)

torch.save(model, 'model/model.pth')
